name: Docker

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run Docker container
        run: |
          docker run -d \
            --name my-app-container \
            -p 8080:8080 \
            my-app

      - name: Wait for application
        run: sleep 5

      - name: Test application
        run: curl --fail http://localhost:8080

      - name: Show logs
        if: always()
        run: docker logs my-app-container
